---
- hosts: django-webserver  

  tasks:

    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes

    - name: generate locale
      command: locale-gen en_US.UTF-8
      sudo: yes

    - name: install packages
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - build-essential
        - git
        - rsync
        - htop
        - python-pip 
        - python-dev 
        - libpq-dev
        - geoip-bin
        - python-geoip
        - libgeoip-dev
        - binutils
        - python-gdal

      # These pip packages should really be in a requirements.txt, 
      # but this is easier during dev.
    - name: install django and supporting packages
      command: "pip install {{ item }}"
      sudo: yes
      with_items:
              - django-toolbelt
              - django-bootstrap-form
              - django-frontend
              - django-frontend-template
              - django-frontend-skeleton
              - requests
              - south
              - virtualenv
              - geoip

    - name: collect Django static files
      command: "python /vagrant/{{ project_name }}/manage.py collectstatic --noinput"

#    - name: create virtualenv
#      command: "virtualenv --system-site-packages /vagrant/{{ project_name }}/venv"
#
#    - name: activate virtualenv
#      command: "source /vagrant/{{ project_name }}/venv/bin/activate"

#    - name: start django server
#      command: "python /vagrant/{{ project_name }}/manage.py runserver 0.0.0.0:8000"
#      command: "python /vagrant/{{ project_name }}/manage.py runserver [::]:8000"
