---
- hosts: django-webserver  

  tasks:

    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes

    - name: generate locale
      command: locale-gen en_US.UTF-8
      sudo: yes

    - name: install packages
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - build-essential
        - git
        - tree
        - tmux
        - vim
        - curl
        - gnupg
        - zip
        - rsync
        - wget
        - rubygems
        - python-pip 
        - python-dev 
        - libpq-dev
        - rbenv
        - apache2

    - name: install django and supporting packages
      command: "pip install {{ item }}"
      sudo: yes
      with_items:
              - django-toolbelt
              - django-bootstrap-form
              - django-frontend-skeleton
              - south
              - virtualenv

    - name: create virtualenv
      command: "virtualenv --system-site-packages /vagrant/{{ project_name }}/venv"

    - name: activate virtualenv
      command: "source /vagrant/{{ project_name }}/venv/bin/activate"

    - name: start django server
      command: "python /vagrant/{{ project_name }}/manage.py runserver 0.0.0.0:8000 &"
